function txt_opening() {
	msg = msglang([
	
	txt("What an enchanting sight.", SUMIREKO.HAPPY),
	txt("You really don't see anything like this back home in Kanto.", SUMIREKO.NEUTRAL),
	txt("Though there are some things I miss. I wonder..."),
	txt("Ha! What a genius I am!", SUMIREKO.EXTREMEHAPPY),
	txt("Ah, so that's what's making all this noise. And here I wanted a peaceful morning walk.", MOKOU.NEUTRAL),
	txt("Wha--", SUMIREKO.NEUTRAL),
	txt("Oh, it's you, the psychic girl. Usami, was it?", MOKOU.NEUTRAL),
	txt("Y-yes... Usami Sumireko. D-did you really see all that, Mokou?"),
	txt("Hard not to, it was such an obnoxious flash.", MOKOU.FROWN),
	txt("(Aww man, I really could be more subtle.),", SUMIREKO.EXTREMESAD),
	txt("What do you have there?", MOKOU.NEUTRAL),
	txt("Oh, this? A snowboard!", SUMIREKO.SMILE),
	txt("A... Snow Board?", MOKOU.MOUTHOPEN),
	txt("Yes! It's a very popular winter sport back home."),
	txt("How do you play it?", MOKOU.NEUTRAL),
	txt("You don't play it, you ride it.", SUMIREKO.NEUTRAL),
	txt("... Ride it where?", MOKOU.MOUTHOPEN),
	txt("Down a slope, of course.", SUMIREKO.SMILE),
	txt("Huh, I don't see the appeal.", MOKOU.FROWN),
	txt("(Oh, right, everyone flies in these parts, don't they?),", SUMIREKO.NEUTRAL),
	txt("... I could show you if you like.", SUMIREKO.SMILE),
	txt("Hmm, I dunno, feels like I'm liable to get hurt. I really don't want to reincarnate today if it can be helped.", MOKOU.EXTREMESAD),
	txt("Ayayaya, what do we have here?", AYA.EXTREMEHAPPY),
	txt("Oh good, it's the local gossipmonger."),
	txt("Oh c'mon now, Fujiwara-san, I ain't that bad.", AYA.FROWN), 
	txt("I usually come 'round this way in first thing in the morning, and I saw you two here so I figured to say hello!", AYA.HAPPY),
	txt("... I really didn't think I would attract so much attention today. I'm sorry.", SUMIREKO.EXTREMESAD),
	txt("Aha! The famous psychic wunderkind herself, Usami Sumireko! I was wonderin' who sent out that convoluted purple magic out here."),
	txt("What do you want?", MOKOU.FROWN),
	txt("Aww, nothin' much, just lookin' fer scoops for the Bunbunmaru Newspaper, as usual!", AYA.EXTREMEHAPPY),
	txt("Ya know, Usami-chan doesn't really grace us with her presence very often. And what a thing she's holding, too!", AYA.HAPPY),
	txt("You mean my snowboard?", SUMIREKO.NEUTRAL),
	txt("Snow Board... How d'ya play it?", AYA.FROWN),
	txt("You don't play it, you ride it."),
	txt("Is it a popular winter sport where you come from, Usami-chan?"),
	txt("Y-yes, how did you know?", SUMIREKO.HAPPY),
	txt("Ayaya, I heard tell in the winds on the way here. Nothin' escapes the sharp tengu ears of the honorable Shameimaru Aya!", AYA.EXTREMEHAPPY),
	txt("Hey, Usami-chan, could you show me how it works? I've been meanin' ta get some slice-of-life shots for the paper, and this would be perfect!", AYA.HAPPY),
	txt("Sure! I was just telling Mokou how fun it is before you got here!", SUMIREKO.HAPPY),
	txt("..."),
	txt("Aww Fujiwara-san, surely ya can't turn down such an invitation from such a sweet lil' cinnamon roll.", AYA.NEUTRAL),
	txt("(She's got no idea about our history, does she?)"),
	txt("You'd look real dashin' on my camera, too. Whaddaya say, huh?", AYA.EXTREMEHAPPY),
	txt("... I guess it'd be quicker to go down the mountain this way than on foot. Why not?", MOKOU.NEUTRAL),
	txt("Great! Ya mind conjurin' up one for me too? Understandin' things first-hand is part n' parcel of being a good reporter.", AYA.HAPPY),
	txt("You could just say you wanted to join us.", MOKOU.HAPPY),
	txt("Ayaya, I'm on the clock. I gotta ask so's I don't get in trouble."),
	txt("Sure, sure, I can do that for you, Miss Aya."),
	txt("Here you go!"),
	txt("Much obliged!"),
	txt("Thanks."),
	txt("(Oh goodness, I might have to remember how to do actually this.)", SUMIREKO.EXTREMESAD),
	txt("Ready when you are, Usami.", MOKOU.NEUTRAL),
	txt("Hold still you two, I'll make sure to get a good shot before we push off!", AYA.EXTREMELYHAPPY),
	
	],[
	
	txt(""),
	
	]);
	
	endevent = function(), {observer_create(o_charselect)};
}