function txt_opening() {
	se_play(se_wintersound);
	music_set(mus.null);
	msg = msglang([
	
	btxt(bk_title),
	txt("What an enchanting sight.", SUMIREKO.HAPPY),
	txt("You really don't see anything like this back home in Kanto.", SUMIREKO.NEUTRAL),
	txt("Though there are some things I miss. I wonder...", SUMIREKO.NEUTRAL),
	txt("Ha! What a genius I am!", SUMIREKO.EXTREMELYHAPPY),
	txt("Ah, so that's what's making all this noise. And here I wanted a peaceful morning walk.", MOKOU.NEUTRAL),
	txt("Wha--", SUMIREKO.NEUTRAL),
	txt("Oh, it's you, the psychic girl. Usami, was it?", MOKOU.NEUTRAL),
	txt("Y-yes... Usami Sumireko. D-did you really see all that, Mokou?", SUMIREKO.NEUTRAL),
	txt("Hard not to, it was such an obnoxious flash.", MOKOU.FROWN),
	txt("(Aww man, I really could be more subtle.),", SUMIREKO.EXTREMELYSAD),
	txt("What do you have there?", MOKOU.NEUTRAL),
	txt("Oh, this? A snowboard!", SUMIREKO.HAPPY/*was smile*/),
	txt("A... Snow Board?", MOKOU.MOUTHOPEN),
	txt("Yes! It's a very popular winter sport back home.", SUMIREKO.HAPPY),
	txt("How do you play it?", MOKOU.NEUTRAL),
	txt("You don't play it, you ride it.", SUMIREKO.NEUTRAL),
	txt("... Ride it where?", MOKOU.MOUTHOPEN),
	txt("Down a slope, of course.", SUMIREKO.HAPPY/*was smile*/),
	txt("Huh, I don't see the appeal.", MOKOU.FROWN),
	txt("(Oh, right, everyone flies in these parts, don't they?),", SUMIREKO.NEUTRAL),
	txt("... I could show you if you like.", SUMIREKO.HAPPY/*was smile*/),
	txt("Hmm, I dunno, feels like I'm liable to get hurt. I really don't want to reincarnate today if it can be helped.", MOKOU.EXTREMELYSAD),
	txt("Ayayaya, what do we have here?", AYA.EXTREMELYHAPPY),
	txt("Oh good, it's the local gossipmonger.", MOKOU.FROWN),
	txt("Oh c'mon now, Fujiwara-san, I ain't that bad.", AYA.FROWN), 
	txt("I usually come 'round this way in first thing in the morning, and I saw you two here so I figured to say hello!", AYA.HAPPY),
	txt("... I really didn't think I would attract so much attention today. I'm sorry.", SUMIREKO.EXTREMELYSAD),
	txt("Aha! The famous psychic wunderkind herself, Usami Sumireko! I was wonderin' who sent out that convoluted purple magic out here.", AYA.HAPPY),
	txt("What do you want?", MOKOU.FROWN),
	txt("Aww, nothin' much, just lookin' fer scoops for the Bunbunmaru Newspaper, as usual!", AYA.EXTREMELYHAPPY),
	txt("Ya know, Usami-chan doesn't really grace us with her presence very often. And what a thing she's holding, too!", AYA.HAPPY),
	txt("You mean my snowboard?", SUMIREKO.NEUTRAL),
	txt("Snow Board... How d'ya play it?", AYA.FROWN),
	txt("You don't play it, you ride it.", SUMIREKO.NEUTRAL),
	txt("Is it a popular winter sport where you come from, Usami-chan?", AYA.HAPPY),
	txt("Y-yes, how did you know?", SUMIREKO.HAPPY),
	txt("Ayaya, I heard tell in the winds on the way here. Nothin' escapes the sharp tengu ears of the honorable Shameimaru Aya!", AYA.EXTREMELYHAPPY),
	txt("Hey, Usami-chan, could you show me how it works? I've been meanin' ta get some slice-of-life shots for the paper, and this would be perfect!", AYA.HAPPY),
	txt("Sure! I was just telling Mokou how fun it is before you got here!", SUMIREKO.HAPPY),
	txt("..."),
	txt("Aww Fujiwara-san, surely ya can't turn down such an invitation from such a sweet lil' cinnamon roll.", AYA.NEUTRAL),
	txt("(She's got no idea about our history, does she?)", MOKOU.FROWN),
	txt("You'd look real dashin' on my camera, too. Whaddaya say, huh?", AYA.EXTREMELYHAPPY),
	txt("... I guess it'd be quicker to go down the mountain this way than on foot. Why not?", MOKOU.NEUTRAL),
	txt("Great! Ya mind conjurin' up one for me too? Understandin' things first-hand is part n' parcel of being a good reporter.", AYA.HAPPY),
	txt("You could just say you wanted to join us.", MOKOU.HAPPY),
	txt("Ayaya, I'm on the clock. I gotta ask so's I don't get in trouble.", AYA.HAPPY),
	txt("Sure, sure, I can do that for you, Miss Aya.", SUMIREKO.EXTREMELYHAPPY),
	txt("Here you go!", SUMIREKO.HAPPY),
	txt("Much obliged!", AYA.HAPPY),
	txt("Thanks.", MOKOU.HAPPY),
	txt("(Oh goodness, I might have to remember how to do actually this.)", SUMIREKO.EXTREMELYSAD),
	txt("Ready when you are, Usami.", MOKOU.NEUTRAL),
	txt("Hold still you two, I'll make sure to get a good shot before we push off!", AYA.EXTREMELYHAPPY),
	
	],[
	
	btxt(bk_title),
	txt("Que vista encantadora.", SUMIREKO.HAPPY),
	txt("Não tem nada igual lá em casa, em Kanto.", SUMIREKO.NEUTRAL),
	txt("Apesar de ter algumas coisas que sinto falta. Será que...", SUMIREKO.NEUTRAL),
	txt("Ha! Que gênia sou!", SUMIREKO.EXTREMELYHAPPY),
	txt("Ah, então é isso que está fazendo todo esse barulho. E eu aqui querendo uma caminhada tranquila.", MOKOU.NEUTRAL),
	txt("O qu--", SUMIREKO.NEUTRAL),
	txt("Ora, é você, a garota psíquica. Usami, né?", MOKOU.NEUTRAL),
	txt("S-sim… Usami Sumireko. V-você viu tudo aquilo, Mokou?", SUMIREKO.NEUTRAL),
	txt("Difícil não ver, foi um clarão bem desagradável.", MOKOU.FROWN),
	txt("(Ai cara, eu deveria ser mais sutil.),", SUMIREKO.EXTREMELYSAD),
	txt("O que você tem aí?", MOKOU.NEUTRAL),
	txt("Ah, isso? Um snowboard!", SUMIREKO.HAPPY/*was smile*/),
	txt("Um... Snow Board?", MOKOU.MOUTHOPEN),
	txt("Sim! É um esporte de inverno bem popular lá em casa.", SUMIREKO.HAPPY),
	txt("Como você joga isso?", MOKOU.NEUTRAL),
	txt("Você não joga, você anda nele.", SUMIREKO.NEUTRAL),
	txt("... Andar onde?", MOKOU.MOUTHOPEN),
	txt("Ladeira abaixo, é claro.", SUMIREKO.HAPPY/*was smile*/),
	txt("Meh, não parece muito legal.", MOKOU.FROWN),
	txt("(Ah, verdade, todo mundo voa por essas partes, não é mesmo?),", SUMIREKO.NEUTRAL),
	txt("... Eu poderia demonstrar para você, se quiser.", SUMIREKO.HAPPY/*was smile*/),
	txt("Hmm, não sei, parece um pouco arriscado. E seria bom se eu não tivesse que reencarnar hoje.", MOKOU.EXTREMELYSAD),
	txt("Ayayaya, o que temos aqui?", AYA.EXTREMELYHAPPY),
	txt("Ah ótimo, é a fofoqueira local.", MOKOU.FROWN),
	txt("Ah qual é, Fujiwara-san, eu não sou assim.", AYA.FROWN),
	txt("Eu costumo passar aqui cedo de manhã, e eu vi vocês duas aqui então pensei em dizer um oi!", AYA.HAPPY),
	txt("... Eu realmente não esperava que chamaria tanta atenção hoje. Me desculpe.", SUMIREKO.EXTREMELYSAD),
	txt("Aha! A famosa gênia psíquica em carne e osso, Usami Sumireko! Tava pensando quem tinha mandado toda aquela magia roxa.", AYA.HAPPY),
	txt("O que tu quer?", MOKOU.FROWN),
	txt("Ai, nada de mais, só atrás de uns furos pro Jornal Bunbunmanru, o de sempre!", AYA.EXTREMELYHAPPY),
	txt("Sabe, não é sempre que a Usami-chan nos dá a graça de sua presença por aqui. E ela tá segurando um troço também!", AYA.HAPPY),
	txt("Você quer dizer meu snowboard?", SUMIREKO.NEUTRAL),
	txt("Snow Board... Como se joga isso?", AYA.FROWN),
	txt("Você não joga, você anda nele.", SUMIREKO.NEUTRAL),
	txt("Não é um esporte de inverno popular de onde você veio, Usami-chan?", AYA.HAPPY),
	txt("S-sim, como você sabia disso?", SUMIREKO.HAPPY),
	txt("Ayaya, eu ouvi nos ventos por aí. Nada escapa as orelhas afiadas de tengu da honorável Shameimaru Aya!", AYA.EXTREMELYHAPPY),
	txt("Ei, Usami-chan, pode me mostrar como isso funciona? Eu tava querendo tirar umas fotos do cotidiano pro jornal, e isso seria perfeito!", AYA.HAPPY),
	txt("Claro! Eu estava falando para a Mokou quão divertido é antes de você chegar aqui.", SUMIREKO.HAPPY),
	txt("..."),
	txt("Aii Fujiwara-san, não tem como você recusar um convite de uma docinho de coco dessas.", AYA.NEUTRAL),
	txt("(Ela não faz ideia do nosso passado, hein?)", MOKOU.FROWN),
	txt("Você ficaria bem maneira na foto também. Que tal, hein?", AYA.EXTREMELYHAPPY),
	txt("... Acho que seria mais rápido descer a montanha desse jeito do que a pé. Por que não?", MOKOU.NEUTRAL),
	txt("Ótimo! Se importa em conjurar um pra mim também? Entender essas coisas botando a mão na massa é essencial para ser uma boa repórter.", AYA.HAPPY),
	txt("Só fala que você queria se juntar à nós logo.", MOKOU.HAPPY), 
	txt("Ayaya, Tô no meu expediente. Preciso perguntar pra não me encrencar.", AYA.HAPPY), 
	txt("Claro, claro, eu posso fazer isso por você, senhorita Aya.", SUMIREKO.EXTREMELYHAPPY), 
	txt("Aqui está!", SUMIREKO.HAPPY),
	txt("Agradecida!", AYA.HAPPY),
	txt("Valeu.", MOKOU.HAPPY), 
	txt("(Minha nossa, eu vou ter que lembrar como fazer isso.),", SUMIREKO.EXTREMELYSAD), 
	txt("Pronta quando você estiver, Usami.", MOKOU.NEUTRAL),
	txt("Pera aí vocês duas, vou garantir de tirar uma foto boa antes de descermos!", AYA.EXTREMELYHAPPY),
	
	],[
	
	btxt(bk_title),
	txt("Qué espectáculo tan encantador.", SUMIREKO.HAPPY),
	txt("Realmente no se ve nada como esto en Kanto.", SUMIREKO.NEUTRAL),
	txt("Aunque hay algunas cosas que echo de menos. Me pregunto...", SUMIREKO.NEUTRAL),
	txt("¡Ja! Qué genio soy.", SUMIREKO.EXTREMELYHAPPY),
	txt("Ah, así que eso es lo que está haciendo todo este ruido. Y todo lo que quería era un tranquilo paseo matutino.", MOKOU.NEUTRAL),
	txt("Que--", SUMIREKO.NEUTRAL),
	txt(">Oh, eres tú, la chica psíquica. Usami, ¿verdad?", MOKOU.NEUTRAL),
	txt("S-si... Usami Sumireko. ¿R-realmente viste todo eso, Mokou?", SUMIREKO.NEUTRAL),
	txt("Difícil no hacerlo, fue un destello tan ridículo.", MOKOU.FROWN),
	txt("(Tengo que ser más sutil.)", SUMIREKO.EXTREMELYSAD),
	txt("¿Qué tienes ahí?", MOKOU.NEUTRAL),
	txt("¿Esto? Un snowboard!", SUMIREKO.HAPPY/*was smile*/),
	txt("Un... Snow Board?", MOKOU.MOUTHOPEN),
	txt("Si! Es un deporte de invierno muy popular en mi país.", SUMIREKO.HAPPY),
	txt("¿Cómo se toca?", MOKOU.NEUTRAL),
	txt("No se juega, se monta.", SUMIREKO.NEUTRAL),
	txt("... ¿Montarlo dónde?", MOKOU.MOUTHOPEN),
	txt("Por una pendiente, por supuesto.", SUMIREKO.HAPPY/*was smile*/),
	txt("Huh, no veo el atractivo.", MOKOU.FROWN),
	txt("(Se me olvidaba, todo el mundo vuela por estos lares...)", SUMIREKO.NEUTRAL),
	txt("... Podría mostrarte si quieres.", SUMIREKO.HAPPY/*was smile*/),
	txt("Hmm, no sé, siento que podría hacerme daño. Realmente no quiero reencarnarme hoy si se puede evitar.", MOKOU.EXTREMELYSAD),
	txt("Ayayaya, ¿qué tenemos aquí?", AYA.EXTREMELYHAPPY),
	txt("Genial, es el entrometido local.", MOKOU.FROWN),
	txt("Vamos, Srta. Fujiwara, no soy tan malo. ", AYA.FROWN) ,
	txt("Suelo venir por aquí a primera hora de la mañana, y os he visto a los dos aquí, ¡así que he pensado en saludaros!", AYA.HAPPY),
	txt("... La verdad es que no pensé que hoy llamaría tanto la atención. Lo siento mucho. ", SUMIREKO.EXTREMELYSAD),
	txt("¡Ajá! ¡La famosa niña prodigio de la videncia, Usami Sumireko! Me preguntaba quién había enviado esa enrevesada magia púrpura hasta aquí.", AYA.HAPPY),
	txt("¿Qué queréis?", MOKOU.FROWN),
	txt("Aww, no mucho, sólo busco primicias para el periódico Bunbunmaru, como siempre.", AYA.EXTREMELYHAPPY),
	txt("Tu sabes, no es frecuente que Usami aparezca por aquí. ¡Y qué cosa lleva en la mano!", AYA.HAPPY),
	txt("¿Te refieres a mi tabla de snowboard?", SUMIREKO.NEUTRAL),
	txt("Snow Board... ¿Cómo lo juegas?", AYA.FROWN),
	txt("No se juega, se monta.", SUMIREKO.NEUTRAL),
	txt("¿Es un deporte de invierno popular de donde vienes, Usami?", AYA.HAPPY),
	txt("S-sí, ¿cómo lo supiste?", SUMIREKO.HAPPY),
	txt("Ayaya, lo oí decir en los vientos de camino hacia aquí. ¡Nada escapa a los agudos oídos tengu de la honorable Shameimaru Aya!", AYA.EXTREMELYHAPPY),
	txt("¿Podrías enseñarme cómo funciona? Quiero hacer unas fotos de la vida cotidiana para el periódico, ¡y esto sería perfecto!", AYA.HAPPY),
	txt("¡Claro! ¡Le estaba contando a Mokou lo divertido que es antes de que llegaras!", SUMIREKO.HAPPY),
	txt("..."),
	txt("Awww, Srta. Fujiwara, seguro que no puede rechazar la invitación de un pequeño rolla de canela...", AYA.NEUTRAL),
	txt("(No tiene ni idea de nuestra historia, ¿verdad?)", MOKOU.FROWN),
	txt("También te verías muy elegante en mi cámara. ¿Qué dices, eh?", AYA.EXTREMELYHAPPY),
	txt("... Supongo que sería más rápido bajar la montaña así que a pie. ¿Por qué no?", MOKOU.NEUTRAL),
	txt("¡Estupendo! ¿Te importaría conjurar uno para mí también? Entender las cosas de primera mano forma parte de ser un buen reportero.", AYA.HAPPY),
	txt("Podrías simplemente decir que quieres unirte a nosotros.", MOKOU.HAPPY),
	txt("Ayaya, voy contrarreloj. Tengo que preguntar para no meterme en problemas.", AYA.HAPPY),
	txt("Vale vale, puedo hacerlo por usted, Srta. Aya.", SUMIREKO.EXTREMELYHAPPY),
	txt("Aquí tienes.", SUMIREKO.HAPPY),
	txt("¡Muchas gracias!", AYA.HAPPY),
	txt("Gracias.", MOKOU.HAPPY),
	txt("(Ay dios mio, puede que tenga que recordar cómo se hace esto en realidad.)", SUMIREKO.EXTREMELYSAD),
	txt("Cuando quieras, Usami.", MOKOU.NEUTRAL),
	txt("Quietos los dos, ¡me aseguraré de hacer una buena toma antes de salir!", AYA.EXTREMELYHAPPY),
	
	]);
	
	endevent = function() {
		audio_stop_all();
		observer_create(o_charselect)
	};
}