function txt_opening() {
	msg = msglang([
	
	txt("What an enchanting sight.", SUMIREKO.HAPPY),
	txt("You really don't see anything like this back home in Kanto.", SUMIREKO.NEUTRAL),
	txt("Though there are some things I miss. I wonder..."),
	txt("Ha! What a genius I am!", SUMIREKO.EXTREMELYHAPPY),
	txt("Ah, so that's what's making all this noise. And here I wanted a peaceful morning walk.", MOKOU.NEUTRAL),
	txt("Wha--", SUMIREKO.NEUTRAL),
	txt("Oh, it's you, the psychic girl. Usami, was it?", MOKOU.NEUTRAL),
	txt("Y-yes... Usami Sumireko. D-did you really see all that, Mokou?"),
	txt("Hard not to, it was such an obnoxious flash.", MOKOU.FROWN),
	txt("(Aww man, I really could be more subtle.),", SUMIREKO.EXTREMELYSAD),
	txt("What do you have there?", MOKOU.NEUTRAL),
	txt("Oh, this? A snowboard!", SUMIREKO.HAPPY/*was smile*/),
	txt("A... Snow Board?", MOKOU.MOUTHOPEN),
	txt("Yes! It's a very popular winter sport back home."),
	txt("How do you play it?", MOKOU.NEUTRAL),
	txt("You don't play it, you ride it.", SUMIREKO.NEUTRAL),
	txt("... Ride it where?", MOKOU.MOUTHOPEN),
	txt("Down a slope, of course.", SUMIREKO.HAPPY/*was smile*/),
	txt("Huh, I don't see the appeal.", MOKOU.FROWN),
	txt("(Oh, right, everyone flies in these parts, don't they?),", SUMIREKO.NEUTRAL),
	txt("... I could show you if you like.", SUMIREKO.HAPPY/*was smile*/),
	txt("Hmm, I dunno, feels like I'm liable to get hurt. I really don't want to reincarnate today if it can be helped.", MOKOU.EXTREMELYSAD),
	txt("Ayayaya, what do we have here?", AYA.EXTREMELYHAPPY),
	txt("Oh good, it's the local gossipmonger."),
	txt("Oh c'mon now, Fujiwara-san, I ain't that bad.", AYA.FROWN), 
	txt("I usually come 'round this way in first thing in the morning, and I saw you two here so I figured to say hello!", AYA.HAPPY),
	txt("... I really didn't think I would attract so much attention today. I'm sorry.", SUMIREKO.EXTREMELYSAD),
	txt("Aha! The famous psychic wunderkind herself, Usami Sumireko! I was wonderin' who sent out that convoluted purple magic out here."),
	txt("What do you want?", MOKOU.FROWN),
	txt("Aww, nothin' much, just lookin' fer scoops for the Bunbunmaru Newspaper, as usual!", AYA.EXTREMELYHAPPY),
	txt("Ya know, Usami-chan doesn't really grace us with her presence very often. And what a thing she's holding, too!", AYA.HAPPY),
	txt("You mean my snowboard?", SUMIREKO.NEUTRAL),
	txt("Snow Board... How d'ya play it?", AYA.FROWN),
	txt("You don't play it, you ride it."),
	txt("Is it a popular winter sport where you come from, Usami-chan?"),
	txt("Y-yes, how did you know?", SUMIREKO.HAPPY),
	txt("Ayaya, I heard tell in the winds on the way here. Nothin' escapes the sharp tengu ears of the honorable Shameimaru Aya!", AYA.EXTREMELYHAPPY),
	txt("Hey, Usami-chan, could you show me how it works? I've been meanin' ta get some slice-of-life shots for the paper, and this would be perfect!", AYA.HAPPY),
	txt("Sure! I was just telling Mokou how fun it is before you got here!", SUMIREKO.HAPPY),
	txt("..."),
	txt("Aww Fujiwara-san, surely ya can't turn down such an invitation from such a sweet lil' cinnamon roll.", AYA.NEUTRAL),
	txt("(She's got no idea about our history, does she?)"),
	txt("You'd look real dashin' on my camera, too. Whaddaya say, huh?", AYA.EXTREMELYHAPPY),
	txt("... I guess it'd be quicker to go down the mountain this way than on foot. Why not?", MOKOU.NEUTRAL),
	txt("Great! Ya mind conjurin' up one for me too? Understandin' things first-hand is part n' parcel of being a good reporter.", AYA.HAPPY),
	txt("You could just say you wanted to join us.", MOKOU.HAPPY),
	txt("Ayaya, I'm on the clock. I gotta ask so's I don't get in trouble."),
	txt("Sure, sure, I can do that for you, Miss Aya."),
	txt("Here you go!"),
	txt("Much obliged!"),
	txt("Thanks."),
	txt("(Oh goodness, I might have to remember how to do actually this.)", SUMIREKO.EXTREMELYSAD),
	txt("Ready when you are, Usami.", MOKOU.NEUTRAL),
	txt("Hold still you two, I'll make sure to get a good shot before we push off!", AYA.EXTREMELYHAPPY),
	
	],[
	
	txt("Que vista encantadora.", SUMIREKO.HAPPY),
	txt("Não tem nada igual lá em casa, em Kanto.", SUMIREKO.NEUTRAL),
	txt("Apesar de ter algumas coisas que sinto falta. Será que..."),
	txt("Ha! Que gênia sou!", SUMIREKO.EXTREMELYHAPPY),
	txt("Ah, então é isso que está fazendo todo esse barulho. E eu aqui querendo uma caminhada tranquila."),
	txt("O qu--", SUMIREKO.NEUTRAL),
	txt("Ora, é você, a garota psíquica. Usami, né?", MOKOU.NEUTRAL),
	txt("S-sim… Usami Sumireko. V-você viu tudo aquilo, Mokou?"),
	txt("Difícil não ver, foi um clarão bem desagradável.", MOKOU.FROWN),
	txt("(Ai cara, eu deveria ser mais sutil.),", SUMIREKO.EXTREMELYSAD),
	txt("O que você tem aí?", MOKOU.NEUTRAL),
	txt("Ah, isso? Um snowboard!", SUMIREKO.HAPPY/*was smile*/),
	txt("Um... Snow Board?", MOKOU.MOUTHOPEN),
	txt("Sim! É um esporte de inverno bem popular lá em casa."),
	txt("Como você joga isso?", MOKOU.NEUTRAL),
	txt("Você não joga, você anda nele.", SUMIREKO.NEUTRAL),
	txt("... Andar onde?", MOKOU.MOUTHOPEN),
	txt("Ladeira abaixo, é claro.", SUMIREKO.HAPPY/*was smile*/),
	txt("Meh, não parece muito legal.", MOKOU.FROWN),
	txt("(Ah, verdade, todo mundo voa por essas partes, não é mesmo?),", SUMIREKO.NEUTRAL),
	txt("... Eu poderia demonstrar para você, se quiser.", SUMIREKO.HAPPY/*was smile*/),
	txt("Hmm, não sei, parece um pouco arriscado. E seria bom se eu não tivesse que reencarnar hoje.", MOKOU.EXTREMELYSAD),
	txt("Ayayaya, o que temos aqui?", AYA.EXTREMELYHAPPY),
	txt("Ah ótimo, é a fofoqueira local."),
	txt("Ah qual é, Fujiwara-san, eu não sou assim.", AYA.FROWN),
	txt("Eu costumo passar aqui cedo de manhã, e eu vi vocês duas aqui então pensei em dizer um oi!", AYA.HAPPY),
	txt("... Eu realmente não esperava que chamaria tanta atenção hoje. Me desculpe.", SUMIREKO.EXTREMELYSAD),
	txt("Aha! A famosa gênia psíquica em carne e osso, Usami Sumireko! Tava pensando quem tinha mandado toda aquela magia roxa."),
	txt("O que tu quer?", MOKOU.FROWN),
	txt("Ai, nada de mais, só atrás de uns furos pro Jornal Bunbunmanru, o de sempre!", AYA.EXTREMELYHAPPY),
	txt("Sabe, não é sempre que a Usami-chan nos dá a graça de sua presença por aqui. E ela tá segurando um troço também!", AYA.HAPPY),
	txt("Você quer dizer meu snowboard?", SUMIREKO.NEUTRAL),
	txt("Snow Board... Como se joga isso?", AYA.FROWN),
	txt("Você não joga, você anda nele."),
	txt("Não é um esporte de inverno popular de onde você veio, Usami-chan?"),
	txt("S-sim, como você sabia disso?", SUMIREKO.HAPPY),
	txt("Ayaya, eu ouvi nos ventos por aí. Nada escapa as orelhas afiadas de tengu da honorável Shameimaru Aya!", AYA.EXTREMELYHAPPY),
	txt("Ei, Usami-chan, pode me mostrar como isso funciona? Eu tava querendo tirar umas fotos do cotidiano pro jornal, e isso seria perfeito!", AYA.HAPPY),
	txt("Claro! Eu estava falando para a Mokou quão divertido é antes de você chegar aqui.", SUMIREKO.HAPPY),
	txt("..."),
	txt("Aii Fujiwara-san, não tem como você recusar um convite de uma docinho de coco dessas.", AYA.NEUTRAL),
	txt("(Ela não faz ideia do nosso passado, hein?)"),
	txt("Você ficaria bem maneira na foto também. Que tal, hein?", AYA.EXTREMELYHAPPY),
	txt("... Acho que seria mais rápido descer a montanha desse jeito do que a pé. Por que não?", MOKOU.NEUTRAL),
	txt("Ótimo! Se importa em conjurar um pra mim também? Entender essas coisas botando a mão na massa é essencial para ser uma boa repórter.", AYA.HAPPY),
	txt("Só fala que você queria se juntar à nós logo.", MOKOU.HAPPY), 
	txt("Ayaya, Tô no meu expediente. Preciso perguntar pra não me encrencar."), 
	txt("Claro, claro, eu posso fazer isso por você, senhorita Aya."), 
	txt("Aqui está!"),
	txt("Agradecida!"),
	txt("Valeu."), 
	txt("(Minha nossa, eu vou ter que lembrar como fazer isso.),", SUMIREKO.EXTREMELYSAD), 
	txt("Pronta quando você estiver, Usami.", MOKOU.NEUTRAL),
	txt("Pera aí vocês duas, vou garantir de tirar uma foto boa antes de descermos!", AYA.EXTREMELYHAPPY),
	
	],[
	

	
	]);
	
	endevent = function() {observer_create(o_charselect)};
}